<?php

/**
 * @var Codifi\CustomerRequest\Block\Request\Form $block
 */
?>
<div>
    <h2>Hello World</h2>
    <form id="my-form"  data-mage-init='{"validation":{"rules": {"fieldtext": {"validate-min-ten":true}}}}'>
        <input type="text" name="fieldtext" id="field-4" >
        <input type="submit" value="Show Message" style="margin-top: 20px;">
    </form>

    <form style="margin-top: 50px;" id="my-form2"  data-mage-init='{"validation":{"rules": {"myFile": {"onlyimages":true}}}}' >
        <input name="myFile" type="file" >
        <input type="submit" value="Upload image" style="margin-top: 20px;">
    </form>

    <form style="margin-top: 50px;" id="my-form3"  data-mage-init='{"validation":{"rules": {"cars2": {"validate-car":true}}}}' >
        <label for="cars">Choose a car:</label>
        <select name="cars2" id="cars2">
            <option value>Please select a car</option>
            <option value="volvo">Volvo</option>
            <option value="saab">Saab</option>
            <option value="opel">Opel</option>
            <option value="audi">Audi</option>
        </select>
        <br><br>
        <input type="submit" value="Submit" style="margin-top: 20px;">
    </form>

</div>

