<div data-bind="scope: 'custom-component'">
    <h2 data-bind="text: title"></h2>
    <p data-bind="text: customText"></p>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "custom-component": {
                        "component": "Codifi_UiComponents/js/component",
                        "title" : "Hello World!"
                        }
                    }
                }
            }
    }
</script>
