<div class="custom-form">
    <form id="customForm">
        <label for="tname">Text</label>
        <input type="text" id="tname" name="text" placeholder="Input text.." required style="margin-bottom: 20px;">

        <br>

        <input name="myFile" type="file" style="margin-bottom: 20px;">

        <br>

        <input type="radio" id="errorMessage" name="message">
        <label for="errorMessage">Error Message</label >

        <br>

        <input type="radio" id="successMessage" name="message">
        <label for="successMessage"> Success Message</label>

        <br>

        <input type="submit" value="Show Message" style="margin-top: 20px;">
    </form>

    <form style="margin-top: 50px;">
        <label for="cars">Choose a pet:</label>
        <select name="housepets">
            <option value="cat">Cat</option>
            <option value="dog">Dog</option>
            <option value="llama">Llama</option>
            <option value="rabbit">Rabbit</option>
            <option value="animal">Animal</option>
        </select>
    </form>

    <form style="margin-top: 50px;">
        <label for="cars">Choose a car:</label>
        <select name="cars" id="cars">
            <option value="volvo">Volvo</option>
            <option value="saab">Saab</option>
            <option value="opel">Opel</option>
            <option value="audi">Audi</option>
        </select>
        <br><br>
        <input type="submit" value="Submit">
    </form>

    <p style="margin-top: 50px;">
        <input type="text" id="datepickecker" placeholder="YYYY-MM-DD" >
    </p>

</div>
